collections:
  - name: microsoft.sql
    src: https://aap-pah1.ekeberg.io/api/galaxy/content/rh-certified/
  - name: redhat.rhel_system_roles
    version: '>= 1.20.0'
    src: https://aap-pah1.ekeberg.io/api/galaxy/content/rh-certified/
